### ISSUE TITLE
Most Recent video NOT updating.

### ISSUE THREAD

**Issue by JayChrawnna** [TheKusamarian/stake-n-vote#23]
The embedded youtube video should be the most recent from the SER playlist on the channel but seems to be stuck on episode 274.

In the mean time I could manually add the url into the code if the location can be pointed out to me!

**Comment by Tur1ngM4ch1n3** [comment]
hi, never used typescript but I'll try to give my opinion, from the release dates of the video and update I'd say it's a caching problem in node-cache
https://github.com/TheKusamarian/stake-n-vote/blob/ed9da696e7b1183f59d227e1e2b4d510f1fe6527/app/lib/latest-yt.ts#L5
the _cacheKey_ was initialized with the _playlistId_ making it static, it has not moved since the update, it should be associated with each videoID.
TM.

**Comment by Tur1ngM4ch1n3** [comment]
Mmm the cache is set to expire after one hour, atm I'm not able to reproduce the issue locally, is this a problem with the **node-cache** libraries on production server only?

**Comment by niklasp** [comment]
Fixed. We are not using vercel, issue coule BE related to that. Disabled Server Side Caching totally and Just Cache in the Client. Lets See If YouTube API allows.
